version: '3'

services:
  backend: ##
    container_name: backend
    build:
      context: ./server
    ports:
      - '5000:5000' # host:container
    networks:
      - app-network

  client:
    build:
      context: ./client
    container_name: client
    ports:
      - '3000:3000'
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
